### ISSUE TITLE
Vendored GEOS lib

### ISSUE THREAD

**Issue by curldivergence** [georust/geos-sys#20]
Hello, thanks for maintaining this crate :) I've got a question though - is there any intention to distribute GEOS alongside these bindings (for example, by adding "vendored" package feature) and build/link it during `cargo build`? It would simplify life of Windows users like me :)

**Comment by gauteh** [comment]
Hi, would you be interested in a PR for this? See e.g.: https://github.com/georust/netcdf for an example of how that works. Maybe use the `static` feature flag to stay in line with `netcdf` and `rust-hdf5`.

**Comment by GuillaumeGomez** [comment]
I think this is solved? Don't hesitate to reopen it if not.
